name: SonarQube Analysis
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Create requirements.txt if missing
        run: |
          if [ ! -f "requirements.txt" ]; then
            echo "Creating default requirements.txt"
            echo "Django>=4.2" > requirements.txt
            echo "djangorestframework>=3.14" >> requirements.txt
            echo "psycopg2-binary>=2.9" >> requirements.txt
          fi
          cat requirements.txt  # Для дебагінга
          
      - name: Install dependencies
        run: pip install -r requirements.txt
